version: '3.4'

services:
  fc.codeflix.catalog.db:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    ports:
      - 3307:3307   
    environment:
      MYSQL_ROOT_PASSWORD: codeflix